module.exports = [
  'constructor()',
  'event AccountCreated(address addr, uint256 index)',
  'event AccountDeleted(address addr, uint256 index)',
  'function create(uint256 index)',
  'function destroy(address recipient)',
  'function destroy(uint256 index, address recipient)',
  'function destroyBatch(uint256[] index, address[] recipient)',
  'function grantRole(bytes32 role, address account)',
  'function renounceRole(bytes32 role, address account)',
  'function revokeRole(bytes32 role, address account)',
  'event RoleAdminChanged(bytes32 indexed role, bytes32 indexed previousAdminRole, bytes32 indexed newAdminRole)',
  'event RoleGranted(bytes32 indexed role, address indexed account, address indexed sender)',
  'event RoleRevoked(bytes32 indexed role, address indexed account, address indexed sender)',
  'function swap(uint256 index, uint256 method, address router, uint256 amountIn, uint256 amountOutMin, address[] path, address to)',
  'function swapBatch(uint256[] index, uint256[] method, address[] router, uint256[] amountIn, uint256[] amountOutMin, address[][] path, address[] to)',
  'function transfer(uint256 index, address recipient, address assetAddress, uint256 amount)',
  'function transferBatch(uint256[] index, address[] recipient, address[] assetAddress, uint256[] amount)',
  'function ACCOUNT_ROLE() view returns (bytes32)',
  'function accounts(bytes32) view returns (address)',
  'function DEFAULT_ADMIN_ROLE() view returns (bytes32)',
  'function get(uint256 index) view returns (address addr, bool exists, bytes32 salt)',
  'function getRoleAdmin(bytes32 role) view returns (bytes32)',
  'function hasRole(bytes32 role, address account) view returns (bool)',
  'function modelAccount() view returns (address)',
  'function supportsInterface(bytes4 interfaceId) view returns (bool)'
]
